[project]
name = "paper-cost-simulator"
version = "0.1.0"
description = "A streamlit application to visualise the cost of knowledge."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "drawsvg>=2.4.2",
    "kaleido>=1.4.0",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "plotly>=6.6.0",
    "resvg-py>=0.5.0",
    "streamlit[charts]>=1.56.0",
]
